apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-tpsrv
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs"
  nfs:
    # server: nfs-server.cta.svc.cluster.local
    # server: {{ .Values.nfs_server_ip }}
    server: SERVERIP
    path: "/"
